version: '3'
services:
    backend:
        build:
            context: '.'
            dockerfile: './docker/backend.dockerfile'
        volumes:
            - './server/docker.config.json:/app/server/config.json:ro'
            - './server/logs:/app/server/logs'
            - '~/.aws/credentials:/root/.aws/credentials:ro'
        ports: 
            - '10000:10000'

    frontend:
        build: 
            context: '.'
            dockerfile: './docker/frontend.dockerfile'
            args:
                APP_PATH: /
        environment:
            API_BASE_URL: http://backend:10000
            APP_PATH: /
        ports: 
            - '3000:80'

    database-import:
        build:
            context: '.'
            dockerfile: './docker/database.dockerfile'
        volumes:
            - './server/docker.config.json:/app/database/config.json:ro'
            - './database/logs:/app/database/logs'
            - '~/.aws/credentials:/root/.aws/credentials:ro'

    database:
        image: postgres
        environment:
            POSTGRES_USER: methylscape
            POSTGRES_PASSWORD: methylscape
            POSTGRES_DB: methylscape
        ports:
          - '5432:5432'
